name: CI-CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Pegar os arquivos
        uses: actions/checkout@v4
      - name: Autenticar no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./src
          push: true
          tags: |
            lucasccorrea/fake-shop:v${{github.run_number}}
            lucasccorrea/fake-shop:latest

  cd:
    runs-on: ubuntu-latest
    needs: [ci]
    steps:
      - name: Autenticar na AWS
        run: echo "Executando o camando AWS configure"
